# Generated by Django 2.0.7 on 2018-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(max_length=100, verbose_name='头像'),
        ),
    ]
