# Generated by Django 2.0.7 on 2018-09-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_signon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'rigister'), ('forget', 'forget')], max_length=10, verbose_name='发送类型'),
        ),
    ]
