# Generated by Django 2.0.7 on 2018-09-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travermsg',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city_id', to='TraverMsg.CityMsg', verbose_name='目标城市'),
        ),
        migrations.AlterField(
            model_name='travermsg',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city_id', to='TraverMsg.CityMsg', verbose_name='开始城市'),
        ),
    ]
