# Generated by Django 2.0.7 on 2018-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenicmsg',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='scenicmsg',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='scenicmsg',
            name='scenic_content',
        ),
        migrations.AddField(
            model_name='scenicmsg',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在城市'),
        ),
    ]
