# Generated by Django 2.0.7 on 2018-09-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0002_auto_20180909_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceMsg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='省份id')),
                ('name', models.CharField(max_length=20, verbose_name='省份名称')),
                ('province_content', models.CharField(max_length=500, verbose_name='省份简介')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片url')),
            ],
            options={
                'verbose_name': '省份信息',
                'verbose_name_plural': '省份信息',
            },
        ),
        migrations.AlterField(
            model_name='citymsg',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ProvinceMsg', verbose_name='所属省份'),
        ),
    ]
