# Generated by Django 2.0.7 on 2018-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0002_auto_20180914_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travermsg',
            name='end_city',
        ),
        migrations.RemoveField(
            model_name='travermsg',
            name='start_city',
        ),
        migrations.RemoveField(
            model_name='travermsg',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='citymsg',
            name='city_content',
        ),
        migrations.RemoveField(
            model_name='citymsg',
            name='province',
        ),
        migrations.RemoveField(
            model_name='provincemsg',
            name='province_content',
        ),
        migrations.AddField(
            model_name='citymsg',
            name='province_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属省份'),
        ),
        migrations.AddField(
            model_name='scenicmsg',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='scenicmsg',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属城市'),
        ),
        migrations.DeleteModel(
            name='TraverMsg',
        ),
    ]
