# Generated by Django 2.0.7 on 2018-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0003_auto_20180914_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymsg',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='provincemsg',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='省份名称'),
        ),
    ]
