# Generated by Django 2.0.7 on 2018-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0003_auto_20180909_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymsg',
            name='city_content',
            field=models.CharField(max_length=500, null=True, verbose_name='城市简介'),
        ),
        migrations.AlterField(
            model_name='citymsg',
            name='img_url',
            field=models.CharField(max_length=100, null=True, verbose_name='首页图片url'),
        ),
        migrations.AlterField(
            model_name='provincemsg',
            name='img_url',
            field=models.CharField(max_length=100, null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='provincemsg',
            name='province_content',
            field=models.CharField(max_length=500, null=True, verbose_name='省份简介'),
        ),
    ]
