# Generated by Django 2.0.7 on 2018-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0005_auto_20180910_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemsg',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False, verbose_name='省份id'),
        ),
    ]
