# Generated by Django 2.0.7 on 2018-09-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0005_auto_20180915_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymsg',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='首页图片url'),
        ),
        migrations.AlterField(
            model_name='provincemsg',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='scenicmsg',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='scenicmsg',
            name='link_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='景点链接'),
        ),
    ]
