# Generated by Django 2.0.7 on 2018-09-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0006_auto_20180910_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymsg',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False, verbose_name='城市id'),
        ),
        migrations.AlterField(
            model_name='citymsg',
            name='name',
            field=models.IntegerField(verbose_name='城市名称'),
        ),
    ]
