# Generated by Django 2.0.7 on 2018-09-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0007_auto_20180910_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymsg',
            name='name',
        ),
        migrations.AddField(
            model_name='citymsg',
            name='city_id',
            field=models.IntegerField(default=1, verbose_name='城市id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citymsg',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='provincemsg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='省份id'),
        ),
    ]
