# Generated by Django 2.0.7 on 2018-09-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0008_auto_20180910_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymsg',
            name='city_id',
        ),
        migrations.AddField(
            model_name='citymsg',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='城市名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citymsg',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='城市id'),
        ),
    ]
