# Generated by Django 2.0.7 on 2018-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0009_auto_20180910_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemsg',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='省份id'),
        ),
    ]
