# Generated by Django 2.0.7 on 2018-09-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TraverMsg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMsg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='产品id')),
                ('name', models.CharField(max_length=30, verbose_name='产品名称')),
                ('product_price', models.CharField(max_length=10, verbose_name='产品价格')),
                ('product_link', models.CharField(max_length=100, verbose_name='产品链接')),
                ('start_city', models.CharField(max_length=20, verbose_name='开始城市')),
                ('end_city', models.CharField(max_length=20, verbose_name='目的城市')),
                ('avr_price', models.IntegerField(verbose_name='人均价格')),
                ('sell_num', models.IntegerField(verbose_name='产品销量')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='供应商id')),
                ('name', models.CharField(max_length=30, verbose_name='供应商名称')),
                ('link_url', models.CharField(max_length=100, verbose_name='供应商网站链接')),
                ('cooperation_type', models.CharField(choices=[('1', '战略合作'), ('2', '广告代理'), ('3', '数据提供')], default='3', max_length=10, verbose_name='合作类型')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='TicketsMsg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='门票id')),
                ('name', models.CharField(max_length=20, verbose_name='门票名称')),
                ('ticket_content', models.CharField(max_length=3000, verbose_name='门票简介')),
                ('ticket_num', models.IntegerField(verbose_name='门票剩余数量')),
                ('ticket_price', models.CharField(max_length=10, verbose_name='门票价格')),
                ('ticket_url', models.CharField(max_length=100, verbose_name='门票链接')),
                ('scenic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='所属景点')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier', verbose_name='所属供应商')),
            ],
            options={
                'verbose_name': '门票信息',
                'verbose_name_plural': '门票信息',
            },
        ),
        migrations.AddField(
            model_name='productmsg',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier', verbose_name='所属供应商'),
        ),
    ]
