# Generated by Django 2.0.7 on 2018-09-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0002_productmsg_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmsg',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg', verbose_name='开始城市'),
        ),
    ]
