# Generated by Django 2.0.7 on 2018-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0003_auto_20180909_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmsg',
            name='end_city',
        ),
        migrations.RemoveField(
            model_name='productmsg',
            name='start_city',
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='avr_price',
            field=models.CharField(max_length=10, verbose_name='人均价格'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='sell_num',
            field=models.CharField(max_length=10, verbose_name='产品销量'),
        ),
    ]
