# Generated by Django 2.0.7 on 2018-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0003_auto_20180913_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmsg',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='酒店id'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='产品id'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='供应商id'),
        ),
    ]
