# Generated by Django 2.0.7 on 2018-09-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0004_auto_20180913_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmsg',
            name='scenic_id',
        ),
        migrations.AddField(
            model_name='hotelmsg',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在城市'),
        ),
        migrations.AddField(
            model_name='hotelmsg',
            name='scenic_name',
            field=models.CharField(max_length=100, null=True, verbose_name='酒店位置'),
        ),
    ]
