# Generated by Django 2.0.7 on 2018-09-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('TraverMsg', '0002_auto_20180909_1759'),
        ('ProductDT', '0004_auto_20180909_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMsg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='酒店id')),
                ('name', models.CharField(max_length=50, verbose_name='酒店名字')),
                ('type',
                 models.CharField(choices=[('1', '高档酒店'), ('2', '团购'), ('3', '特价酒店'), ('4', '客栈青旅')], default='4',
                                  max_length=20, verbose_name='酒店类型')),
                ('score', models.CharField(max_length=10, verbose_name='酒店评分')),
                ('hotel_price', models.CharField(max_length=10, verbose_name='酒店价格')),
                ('hotel_content', models.CharField(max_length=300, verbose_name='酒店简介')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片url')),
                ('hotel_link', models.CharField(max_length=100, verbose_name='酒店链接')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg',
                                              verbose_name='所属城市')),
                ('scenic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg',
                                                verbose_name='所属景点')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier',
                                                  verbose_name='供应商')),
            ],
            options={
                'verbose_name': '酒店信息',
                'verbose_name_plural': '酒店信息',
            },
        ),
        migrations.RenameField(
            model_name='ticketsmsg',
            old_name='ticket_url',
            new_name='ticket_link',
        ),
    ]
