# Generated by Django 2.0.7 on 2018-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0005_auto_20180914_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsmsg',
            old_name='city_id',
            new_name='city_name',
        ),
        migrations.AlterField(
            model_name='hotelmsg',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属城市'),
        ),
    ]
