# Generated by Django 2.0.7 on 2018-09-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0005_auto_20180909_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmsg',
            name='avr_price',
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='score',
            field=models.CharField(max_length=10, verbose_name='综合评分'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='ticket_num',
            field=models.CharField(max_length=10, verbose_name='门票剩余数量'),
        ),
    ]
