# Generated by Django 2.0.7 on 2018-09-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0003_auto_20180909_2359'),
        ('ProductDT', '0006_auto_20180909_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmsg',
            name='product_type',
            field=models.CharField(choices=[('1', '自驾游'), ('2', '跟团游')], default='1', max_length=10, verbose_name='产品类型'),
        ),
        migrations.AddField(
            model_name='productmsg',
            name='scenic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='景点id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmsg',
            name='start_city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg', verbose_name='出发城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmsg',
            name='traver_days',
            field=models.CharField(default=0, max_length=10, verbose_name='行程天数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='product_price',
            field=models.CharField(max_length=10, verbose_name='起价'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier', verbose_name='供应商'),
        ),
    ]
