# Generated by Django 2.0.7 on 2018-09-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0008_auto_20180910_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategymsg',
            options={'verbose_name': '攻略信息', 'verbose_name_plural': '攻略信息'},
        ),
    ]
