# Generated by Django 2.0.7 on 2018-09-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0009_auto_20180910_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmsg',
            name='city_id',
        ),
    ]
