# Generated by Django 2.0.7 on 2018-09-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0010_remove_hotelmsg_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmsg',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片url'),
        ),
        migrations.AlterField(
            model_name='hotelmsg',
            name='scenic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='所属景点'),
        ),
        migrations.AlterField(
            model_name='hotelmsg',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='酒店评分'),
        ),
        migrations.AlterField(
            model_name='hotelmsg',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='scenic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='景点id'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='综合评分'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='sell_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='产品销量'),
        ),
        migrations.AlterField(
            model_name='strategymsg',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg', verbose_name='相关城市'),
        ),
        migrations.AlterField(
            model_name='strategymsg',
            name='scenic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='相关景点'),
        ),
        migrations.AlterField(
            model_name='strategymsg',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='scenic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='所属景点'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='scense_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='场景地址'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductDT.Supplier', verbose_name='所属供应商'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='ticket_content',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='费用说明'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='ticket_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='门票价格'),
        ),
    ]
