# Generated by Django 2.0.7 on 2018-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0011_auto_20180911_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmsg',
            name='type',
        ),
        migrations.AddField(
            model_name='hotelmsg',
            name='latest_time',
            field=models.CharField(default=1, max_length=100, verbose_name='最新情况'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelmsg',
            name='sell_num',
            field=models.CharField(default=1, max_length=50, verbose_name='酒店人气'),
            preserve_default=False,
        ),
    ]
