# Generated by Django 2.0.7 on 2018-09-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0010_auto_20180911_1040'),
        ('ProductDT', '0012_auto_20180911_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsmsg',
            name='name',
        ),
        migrations.AddField(
            model_name='ticketsmsg',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg', verbose_name='所属城市'),
        ),
        migrations.AddField(
            model_name='ticketsmsg',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='ticketsmsg',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='hotelmsg',
            name='scenic_id',
            field=models.CharField(max_length=100, null=True, verbose_name='所属景点'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='scenic_id',
            field=models.CharField(max_length=50, null=True, verbose_name='所属景点'),
        ),
        migrations.AlterField(
            model_name='ticketsmsg',
            name='ticket_content',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='门票描述'),
        ),
    ]
