# Generated by Django 2.0.7 on 2018-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0014_auto_20180911_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmsg',
            name='scenic_id',
        ),
        migrations.RemoveField(
            model_name='ticketsmsg',
            name='scenic_id',
        ),
        migrations.AddField(
            model_name='productmsg',
            name='comments_num',
            field=models.CharField(default=1, max_length=10, verbose_name='评论数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmsg',
            name='img_url',
            field=models.CharField(default=1, max_length=100, verbose_name='图片url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmsg',
            name='product_grade',
            field=models.CharField(default=1, max_length=10, verbose_name='产品等级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmsg',
            name='scenic_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='景点'),
        ),
        migrations.AddField(
            model_name='ticketsmsg',
            name='scenic_name',
            field=models.CharField(max_length=50, null=True, verbose_name='景点'),
        ),
        migrations.AlterField(
            model_name='productmsg',
            name='start_city',
            field=models.CharField(max_length=30, verbose_name='出发城市'),
        ),
    ]
