# Generated by Django 2.0.7 on 2018-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDT', '0016_auto_20180912_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategymsg',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='strategymsg',
            name='scenic_id',
        ),
        migrations.AddField(
            model_name='strategymsg',
            name='scenic_name',
            field=models.CharField(default=1, max_length=100, verbose_name='相关景点'),
            preserve_default=False,
        ),
    ]
