# Generated by Django 2.0.7 on 2018-09-13 10:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TraverMsg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraverNote',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='游记id')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('note_content', models.CharField(max_length=3000, verbose_name='游记内容')),
                ('star_num', models.CharField(max_length=10, verbose_name='点赞人数')),
                ('notify_status', models.CharField(choices=[('1', '待评审'), ('2', '通过审核')], default='1', max_length=10, verbose_name='审核状态')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发表日期')),
                ('img_url', models.CharField(max_length=100, verbose_name='封面图url')),
                ('scenic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='所属景点')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户游记',
                'verbose_name_plural': '用户游记',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='回复id')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('answer_content', models.CharField(max_length=3000, verbose_name='回答内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户解答',
                'verbose_name_plural': '用户解答',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='问题id')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('ask_content', models.CharField(max_length=11, verbose_name='内容')),
                ('star_num', models.CharField(max_length=50, verbose_name='关注数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('scenic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.ScenicMsg', verbose_name='景点id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户提问',
                'verbose_name_plural': '用户提问',
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraverAsk.UserAsk', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
