# Generated by Django 2.0.7 on 2018-09-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TraverMsg', '0004_auto_20180914_1435'),
        ('TraverAsk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travernote',
            name='scenic_id',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userask',
            name='scenic_id',
        ),
        migrations.AddField(
            model_name='travernote',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg', verbose_name='所属城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userask',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TraverMsg.CityMsg', verbose_name='所属城市id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travernote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Signon', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='add_time',
            field=models.CharField(max_length=100, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Signon', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='add_time',
            field=models.CharField(max_length=100, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='ask_content',
            field=models.CharField(max_length=3000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Signon', verbose_name='所属用户'),
        ),
    ]
