# Generated by Django 2.0.7 on 2018-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverAsk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travernote',
            name='star_num',
            field=models.CharField(max_length=10, verbose_name='点赞人数'),
        ),
    ]
