# Generated by Django 2.0.7 on 2018-09-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraverAsk', '0003_auto_20180917_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travernote',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='游记id'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='add_time',
            field=models.DateTimeField(verbose_name='回答时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='add_time',
            field=models.DateTimeField(verbose_name='发表时间'),
        ),
    ]
